theme: jekyll-theme-midnight

title: KEINOS' Blog
description: Official blog of KEINOS but mostly for my own reference. A Japanese made in Mexico with Mexican quality. Who monkey around the jungle of codes. ;-)
show_downloads: false
